app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from time import time
import jwt
import os
from datetime import datetime
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(40),unique = True, index=True)
    hash_pass = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True, index = True)
    profile_pic_path = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    location = db.Column(db.String(255))
    preferences = db.Column(db.String(255))
    photos = db.relationship('PhotoProfile',backref = 'user',lazy = "dynamic")
    reviews = db.relationship('Review',backref = 'user',lazy = "dynamic")
  

    @property
    def password(self):
        raise AttributeError("You cannot read password attribute")

    @password.setter
    def password(self,password):
        self.hash_pass = generate_password_hash(password)
    
    def set_password(self,password):
        self.hash_pass = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.hash_pass,password)
    
    def get_reset_password_token(self, expires_in=600):
        return jwt.encode({'reset_password':self.id, 'exp':time()+expires_in}, os.environ.get('SECRET_KEY'), algorithm='HS256').decode('utf-8')
    
    @staticmethod
    def verify_reset_password(token):
        try:
            id = jwt.decode(token, os.environ.get('SECRET_KEY'),algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)
    
    def __repr__(self):
        return f'User {self.username}'
class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer,primary_key = True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

class Review(db.Model):

    __tablename__ = 'reviews'
    id = db.Column(db.Integer,primary_key = True)
    book_id = db.Column(db.Integer)
    book_title = db.Column(db.String)
    book_path = db.Column(db.String)
    book_review = db.Column(db.String)
    posted = db.Column(db.Time,default=datetime.utcnow())
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))



    def save_review(self):
        db.session.add(self)
        db.session.commit()



    @classmethod
    def get_reviews(cls,id):

        reviews = Review.query.filter_by(book_id=id).all()
        return reviews

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
   bio = TextAreaField('Tell us about you',validators = [Required()])
   location = TextAreaField('Location',validators = [Required()])
   preferences = TextAreaField('Preferences',validators = [Required()])
   submit = SubmitField('Add Bio')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_simplemde import SimpleMDE
from flask_mail import Mail
from flask_uploads import UploadSet, configure_uploads, IMAGES




# Instances of flask extensions
# Instance of LoginManger and using its methods
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()
simple = SimpleMDE()
mail = Mail()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    '''
    Function that takes configuration setting key as an argument
    
    Args:
        config_name : name of the configuration to be used
    '''

    # Initialising application
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])


    # Initialising flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Regestering the main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Regestering the auth bluprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    # Setting config when using an API
    # from .requests import configure_request
    #configure_request(app)
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User
from .forms import UpdateProfile
from flask_login import login_required
from .. import db,photos

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    title = 'Home'

    return render_template('index.html', title = title )
@main.route('/comic')
@login_required
def comic():
  
    return render_template('comic.html')

@main.route('/motivation')
@login_required
def motivation():
  
    return render_template('motivation.html')

@main.route('/novels')
@login_required
def novels():
  
    return render_template('novels.html')

@main.route('/spiritual')
@login_required
def spiritual():
  
    return render_template('spiritual.html')

@main.route('/fashionentertainment')
@login_required
def fashionentertainment():
  
    return render_template('fashionentertainment.html')


@main.route('/health')
@login_required
def health():
    
    return render_template('health.html')

@main.route('/aboutus')
@login_required
def aboutus():

    '''
    View root page function that returns the about us page and its data
    '''

    title = 'About US'

    return render_template('aboutus.html', title = title )


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data
        user.preferences = form.preferences.data
        user.location = form.location.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/aboutus.html
{% extends 'base.html' %}
{%block content%}
<div class="container" style = "font-size:17px;text-align:center;">
<h1>About us</h1>
<P>Book Review is a free service that helps users discover books they'll love<br>
    while providing authors and publishers.If you like books you will love us<br>
    Its a website designed for book lovers.</P>
<p>You will probably notice that the majority of reviews tend towards the positive<br>
     and this is mainly due to the fact that we choose very carefully which books are<br>
     accepted, there simply is not enough time in the world to read too many badly written books.
</p>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
{%block footer%}
{{super()}}
{%endblock%}
{%endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block styles%}
{{ super() }}
   
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/index.css">
  
{% endblock %}

 <!-- Navbar block  --> 
 {% block navbar %}

 {% include 'navbar.html' %}
 

 {% endblock %}

 {% block scripts %}
 {{ super() }}

 <!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/js/mdb.min.js"></script>

{% endblock %}
{%block footer%}
<footer style="font-size: 17px" class="page-footer font-small stylish-color-dark pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-4 mx-auto">

        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4" href="/">BookReview</h5>
        <p>Here you can read and review books.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
       

        <ul class="list-unstyled">
          <li>
            <a href="/novels">Novels</a>
          </li>
          <li>
            <a href="/comic">Comics</a>
          </li>
          <li>
            <a href="#!">Home</a>
          </li>
         
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
       

        <ul class="list-unstyled">
          <li>
            <a href="/health">Health & Fitness</a>
          </li>
          <li>
            <a href="/spiritual">Spiritual</a>
          </li>
          <li>
            <a href="/aboutus">About</a>
          </li>
         
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
       

        <ul class="list-unstyled">
          <li>
            <a href="/motivation">Motivational</a>
          </li>
          <li>
            <a href="/fashionentertainment">Fashion & Entertainment</a>
          </li>
        
         
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <hr>

  <!-- Call to action -->
  <ul class="list-unstyled list-inline text-center py-2">
    <li class="list-inline-item">
      <h5 class="mb-1">Subscribe for free</h5>
    </li>
    <li class="list-inline-item">
      <a href="{{url_for('auth.register')}}" class="btn btn-info btn-rounded">Sign up!</a>
    </li>
  </ul>
  <!-- Call to action -->

  <hr>

  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a class="btn-floating btn-fb mx-1">
        <i class="fab fa-facebook-f"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-tw mx-1">
        <i class="fab fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-gplus mx-1">
        <i class="fab fa-google-plus-g"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-li mx-1">
        <i class="fab fa-linkedin-in"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-dribbble mx-1">
        <i class="fab fa-dribbble"> </i>
      </a>
    </li>
  </ul>
  <!-- Social buttons -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="/"> BookReview</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
<!--/.Navbar-->

{%endblock%}

app/templates/comic.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="">
            <div class="card ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px"  src="/static/comics/c1.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>The Horror! The Horror! uncovers a rare treasury of some of the most important and neglected stories in American literature—the pre-Code horror comics of the 1950s.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
        <div class="">
            <div class="ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px" src="/static/comics/c13.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>The book opens up with the eeeevil CEO of Oliver Queen’s company trying to conspire against Oliver to the company’s board.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px" src="/static/comics/c3.webp" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>In the stories, Spider-Man is the alias of Peter Parker, an orphan raised by his Aunt May and Uncle Ben in New York City after his parents Richard and Mary Parker were killed in a plane crash.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container-fluid">
    <div class="row">
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px"  src="/static/comics/c4.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>Before Fredric Wertham and The Seduction of the Innocent (SOTI), before the Kefauver Hearings, and before the infamous Comics Code the comic book racks at local drug stores.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px" src="/static/comics/c5.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>The Dark Knight and The Fastest Man Alive, the two greatest detectives on any world, unite to explore the mystery behind a certain blood-stained smiley button embedded in the Batcave wall.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px" src="/static/comics/c6.webp" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>When the character Northstar first came out of the closet in the pages of Alpha Flight back in 1992, he became one of the first openly gay superheroes in mainstream comics. The story itself was a bit of a mess.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container-fluid">
    <div class="row">
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px"  src="/static/comics/c7.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>In his comic book appearances, the character is both the Hulk, a green-skinned, hulking and muscular humanoid possessing a vast degree of physical strength, and his alter ego Dr. Robert Bruce Banner.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px" src="/static/comics/c8.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>Fuelled by his restored faith in humanity, and inspired by Superman's selfless act, Bruce Wayne enlists newfound ally Diana Prince to face an even greater threat.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px" src="/static/comics/c9.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>A cosmic virus has entered our galaxy infecting entire planets. And before it's done, the Man of Steel will have to travel to the ends of the universe to rescue Lois Lane from its corruption.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container-fluid">
    <div class="row">
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px"  src="/static/comics/c10.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>While visiting his mother's grave, Barry Allen, known as the Flash, is alerted to a break-in by his enemies Captain Cold, Captain Boomerang, Heat Wave, Mirror Master, and Top at the Flash Museum.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px" src="/static/comics/c11.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>When Robin's murder investigation casts suspicion on Beast Boy's new employer, Nevrland, Beast Boy finds himself the odd man out on the Teen Titans.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
        <div class="">
            <div class=" ml-4 mt-4" style="width: 40rem;">
                <div class="view overlay zoom">
                    <img class="card-img-top" style="margin-left: auto; margin-right: auto;" height="250px" src="/static/comics/c12.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p style="font-size: 15px" class="card-name"><b>Henched"! Have you been thinking about breaking bad? There's never been a better time help your favorite super-villain take over the world, defeat an archnemesis or rob a bank.</b></p>
                    <a href="https://comiconlinefree.com/" class="btn btn-success btn-rounded mb-4">Read Online</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
</div>
{%block footer%}
{{super()}}
{%endblock%}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <h1>Error Page</h1>
        
    </div>

{% endblock %}

app/templates/navbar.html
<nav style="background-image: url(static/images/bg.jpeg);" class="navbar navbar-expand-lg navbar-dark primary-color">
   
  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a style="font-size: 20px" class="nav-link" href="/"><b>BookReview</b>
          <span class="sr-only">(current)</span>
        </a>
      </li>
     
      <!-- Dropdown -->
     

    </ul>
    <!-- Links -->
    <ul class="navbar-nav navbar-right">
      {% if current_user.is_authenticated%}
      <li class="nav-item" style="font-size:17px;">
          <a class="nav-link" href="{{url_for('main.profile', uname = current_user.username, id_user = current_user.id)}}">{{current_user.username|capitalize}}</a>
      </li>
      <li class="nav-item" style="font-size:17px;">
          <a class="nav-link" href="{{url_for('auth.logout')}}">
              <i class="fa fa-sign-out"></i> Sign out</a>
      </li>
      {% else %}
      <li class="nav-item" style="font-size:18px;">
          <a class="nav-link" href="{{url_for('auth.login')}}">
              <i class="fa fa-sign-in"></i> Sign In</a>
      </li>
      
      {% endif %}
  </ul>
  </div>
  <!-- Collapsible content -->

</nav>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
<br>
<br>
        <div class="span3 well">
        <center>
        <a href="#aboutModal" data-toggle="modal">
            {% if user.profile_pic_path %}
                <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
            <img src="{{url_for('static',filename = 'photos/avatar.png')}}" alt="">
            {% endif %}
            <p class="user-tag"> {{user.username|capitalize}} </p>
            {% if user == current_user %}
            <a><form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
                </form>
                </a>
        </a>
        {% endif %}
         <h3 style="font-size: 20px;color: black;">{{user.username|capitalize}} </h3>
         <em>click my face for more</em>
            </center>
            <div class="modal hide" id="aboutModal">
                <div class="modal-header">
                    <button style="color: blanchedalmond" type="button" class="close" data-dismiss="modal">✕</button>
                </div>
                    <div class="modal-body" style="text-align:center;">
                    <div class="row-fluid">
                        <div class="span10 offset1">
                            <div id="modalTab">
                                <div class="tab-content">
                                    <div class="tab-pane active" id="about">
                                            {% if user.profile_pic_path %}
                                            <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">
                                        {% else %}
                                        <img src="{{url_for('static',filename = 'photos/avatar.png')}}" alt="">
                                        {% endif %}
                                    
      <h3 style="font-size: 20px;color: antiquewhite;" class="media-heading">{{user.username|capitalize}}<small>  {{user.location}} </small></h3>
      <span style="font-size: 20px;color: antiquewhite;"><strong>Preferences</strong></span>
      <p style="font-size: 20px;color: antiquewhite;"> {{user.preferences}} </p>     
    </center>
    <hr>
    <center>
        <div class="col-md-8 stats">
            
            <h3 style="font-size: 20px;color: antiquewhite;">Bio</h3>
            <hr>
            {% if user.bio %}
                <p style="font-size: 20px;color: antiquewhite;"> {{user.bio}} </p>
            {% else %}
                <p style="font-size: 20px;color: antiquewhite;">{{user.username|capitalize}} has no bio</p>
            {% endif %}
            {% if user == current_user %}
            <a class="btn btn-info "  style="font-size: 13px;color: antiquewhite;" href="{{url_for('main.update_profile',uname=user.username)}}">Edit Bio</a>
            <br>
            {% endif %}
            <br>
        </div>
      <br>
      </center>
      </div>
    </div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<!-- <div class="container">
    <div class="row about">
        <div class="col-md-4 picture">
           
            {% if user.profile_pic_path %}
                <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
            <img src="{{url_for('static',filename = 'photos/avatar.png')}}" alt="">
            {% endif %}
            <p class="user-tag"> {{user.username|capitalize}} </p>
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div> -->
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      {{wtf.quick_form(form)}}
    </div>
    <div class="col-md-3"></div>
  </div>
</div>
{% endblock %}